In [50]:
import pandas as pd
import numpy as np
import os
from keras.applications.resnet import decode_predictions

In [5]:
cwd = os.getcwd()
print(cwd)

/Users/ChrisPenny/Documents/MPCS53112/project_dir

In [65]:
df_imagenet_key = pd.read_csv('./ImageNet/imagenet_key.csv')
# display(df_imagenet_key.transpose().reset_index())
df_imagenet_key = df_imagenet_key.transpose().reset_index()
# display(df_imagenet_key)

df_imagenet_key = df_imagenet_key.drop(labels = ['index', 4, 5, 6, 7], axis = 1)
# display(df_imagenet_key)

df_imagenet_key.columns = ['val_id', 'train_id', 'name', 'description']
display(df_imagenet_key)

,val_id,train_id,name,description
0,1,n02119789,"kit fox, Vulpes macrotis",small grey fox of southwestern United States; ...
1,2,n02100735,English setter,an English breed having a plumed tail and a so...
2,3,n02110185,Siberian husky,breed of sled dog developed in northeastern Si...
3,4,n02096294,Australian terrier,small greyish wire-haired breed of terrier fro...
4,5,n02102040,"English springer, English springer spaniel",a breed having typically a black-and-white coat
...,...,...,...,...
2932,1856,n06791372,"signal, signaling, sign",any nonverbal action or gesture that encodes a...
2933,1857,n06873571,visual signal,a signal that involves visual communication
2934,1858,n06874019,light,"a visual warning signal; ""they saw the light o..."
2935,1859,n00031921,relation,an abstraction belonging to or characteristic ...
2936,1860,n13809207,"part, portion, component part, component, cons...",something determined in relation to something ...

In [57]:
# print(df_imagenet_key.columns)
# display(df_imagenet_key[[1]])
# df_imagenet_key[df_imagenet_key[1].str.match('n02966687', na = False)]

In [56]:
class_list = []
id_list = []
description_list = []

for i in range(1000):
    result_vector = np.zeros((1, 1000))
    result_vector[0, i] = 1
    decoded = decode_predictions(result_vector, top=1)
#     print(decoded[0][0])
    class_list.append(int(i))
    id_list.append(decoded[0][0][0])
    description_list.append(decoded[0][0][1])
    
    
df_resnet_key = pd.DataFrame({'resnet_id': id_list, 'resnet_desc': description_list})
# display(df_resnet_key)

     resnet_id        resnet_desc
0    n01440764              tench
1    n01443537           goldfish
2    n01484850  great_white_shark
3    n01491361        tiger_shark
4    n01494475         hammerhead
..         ...                ...
995  n13044778          earthstar
996  n13052670   hen-of-the-woods
997  n13054560             bolete
998  n13133613                ear
999  n15075141      toilet_tissue

[1000 rows x 2 columns]

In [68]:
df_merged_keys = pd.merge(df_imagenet_key, df_resnet_key, how = 'inner', left_on = 'train_id', right_on = 'resnet_id')
display(df_merged_keys)

,val_id,train_id,name,description,resnet_id,resnet_desc
0,1,n02119789,"kit fox, Vulpes macrotis",small grey fox of southwestern United States; ...,n02119789,kit_fox
1,2,n02100735,English setter,an English breed having a plumed tail and a so...,n02100735,English_setter
2,3,n02110185,Siberian husky,breed of sled dog developed in northeastern Si...,n02110185,Siberian_husky
3,4,n02096294,Australian terrier,small greyish wire-haired breed of terrier fro...,n02096294,Australian_terrier
4,5,n02102040,"English springer, English springer spaniel",a breed having typically a black-and-white coat,n02102040,English_springer
...,...,...,...,...,...,...
995,996,n03063599,coffee mug,a mug intended for serving coffee,n03063599,coffee_mug
996,997,n04116512,"rubber eraser, rubber, pencil eraser",an eraser made of rubber (or of a synthetic ma...,n04116512,rubber_eraser
997,998,n04325704,stole,a wide scarf worn about their shoulders by women,n04325704,stole
998,999,n07831146,carbonara,sauce for pasta; contains eggs and bacon or ha...,n07831146,carbonara
999,1000,n03255030,dumbbell,an exercising weight; two spheres connected by...,n03255030,dumbbell

In [69]:
df_merged_keys.to_csv('./ImageNet/imagenet_resnet_key.csv')